"""Immutable normalized extraction contracts."""

from cognoscope.domain.documents.models import (
    AdapterIdentity,
    AdapterOutput,
    BibliographicCandidate,
    BoundingBox,
    BlockKind,
    DocumentPart,
    EvidenceSummary,
    ExtractionAsset,
    ExtractionDiff,
    ExtractionFinding,
    ExtractionRunRecord,
    ExtractionSnapshot,
    ExtractionStatus,
    FindingSeverity,
    NormalizedBlock,
    NormalizedDocument,
    NormalizedPage,
    NormalizedSpan,
    PageMode,
    RepairCandidate,
)

__all__ = [
    "AdapterIdentity",
    "AdapterOutput",
    "BlockKind",
    "BibliographicCandidate",
    "BoundingBox",
    "DocumentPart",
    "ExtractionAsset",
    "ExtractionDiff",
    "ExtractionFinding",
    "ExtractionRunRecord",
    "ExtractionSnapshot",
    "ExtractionStatus",
    "FindingSeverity",
    "EvidenceSummary",
    "NormalizedBlock",
    "NormalizedDocument",
    "NormalizedPage",
    "NormalizedSpan",
    "PageMode",
    "RepairCandidate",
]
